'use strict';

// tests for searchFlight
// Generated by serverless-mocha-plugin

//import {FlightSearchRequest} from "../FlightSearchRequest";

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('searchFlight', '/handler.js', 'findFlight');

describe('searchFlight', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    //let flightSearchRequest = new FlightSearchRequest("", "", "airline3", "", "");
    let flightSearchRequest = {
      'fromAirport': 'fromAirport 1',
      'toAirport': 'toAirport 1',
      'airline' : 'airline3',
      'flightStartDate': 'flightStartDate',
      'flightEndDate': 'flightEndDate'
    };
  return wrapped.run(flightSearchRequest).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});

